### ISSUE TITLE
Open external links to GitHub in the default browser

### ISSUE THREAD

**Issue by leynier** [ManuLpz4/github-app#1]
This can be a solution https://stackoverflow.com/questions/57740574/limiting-url-accessibility-in-flutter-webview-plugin

**Comment by leynier** [comment]
This can be a solution https://stackoverflow.com/questions/57740574/limiting-url-accessibility-in-flutter-webview-plugin

**Comment by leynier** [comment]
You can use [url_launcher](https://pub.dev/packages/url_launcher) package to open external links in the default browser.

**Comment by ManuLpz4** [comment]
Fixed, thank you 😄
https://github.com/ManuLpz4/github-app/commit/58ef5cd759e6f278f1d729a3f755a3cb83291875
